apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web-tcp
  name: web-tcp
spec:
  ports:
    - name: "8098"
      port: 8098
      targetPort: 8098
  selector:
    io.kompose.service: web
  type: LoadBalancer
status:
  loadBalancer: {}
